//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minamb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public System.Guid IdFuncionario { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Profissao { get; set; }
        public int IdTipoDocumento { get; set; }
        public string NumDocumento { get; set; }
        public string Morada { get; set; }
        public int IdMunicipio { get; set; }
        public int IdEstadoCivil { get; set; }
        public int IdGenero { get; set; }
        public string TelefonePrimario { get; set; }
        public string TelefoneAlternativo { get; set; }
        public string Email { get; set; }
        public string NIF { get; set; }
        public bool Estado { get; set; }
    
        public virtual EstadoCivil EstadoCivil { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
