//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minamb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerente
    {
        public System.Guid IdRequerente { get; set; }
        public string Nome { get; set; }
        public string PessoaContacto { get; set; }
        public string TelefonePrimario { get; set; }
        public string TelefoneAlternativo { get; set; }
        public string Email { get; set; }
        public string Endereco { get; set; }
        public int IdMunicipio { get; set; }
        public string ObjetoSocial { get; set; }
        public string CNES { get; set; }
        public string IBGE { get; set; }
        public string UF { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
